type devoteeType  = {
    login_id: string;
    ashery_leader_name: string;
    ashray_leader_initiated_name?: string;
    bhakti_bhikshuk_name:string;
    bhakti_leader_initiated_name?: string;
    name: string;
    email: string;
    contact_number: string;
    Initiated_name: string;
    dob: string;
    have_you_applied_before: string;
    account_approved: string;
    profile_submitted: string;
    devotee_type: string;
    eduction_name: string;
    merital_status_name: string;
    profession_name: string;
    spiritual_master: string;
    current_address: string;
    permanent_address: string;
    Sector_Area: string;
    Socity_Name: string;
    pincode: string;
    how_many_rounds_you_chant: string;
    when_are_you_chantin: string;
    spend_everyday_hearing_lectures: string;
    bakti_shastri_degree: string;
    since_when_you_attending_ashray_classes: string;
    spiritual_master_you_aspiring: string;
    state_name: string;
    district_name: string;
    book_names:string;
    prayer_names:string;
    principle_names:string;
    seminar_names:string;
    SubmitedDate:string;
  };

  export default devoteeType;