type devoteeNextLeveType  = {
    login_id: string;
    ashery_leader_name: string;
    ashray_leader_initiated_name?: string;
    bhakti_bhikshuk_name:string
    bhakti_leader_initiated_name?: string;
    name: string;
    email: string;
    contact_number: string;
    Initiated_name: string;
    dob: string;
    account_approved: string;
    profile_submitted: string;
    devotee_type: string;
    current_address: string;
    Sector_Area: string;
    Socity_Name: string;
    pincode: string;
    state_name: string;
    district_name: string;
    next_level:string;
    level_1_exam_date:string;
    level_1_total_marks:string;
    level_1_obtained_marks:string;
    level_1_is_qualified:string;
    level_2_exam_date:string;
    level_2_total_marks:string;
    level_2_obtained_marks:string;
    level_2_is_qualified:string;
    level_3_exam_date:string;
    level_3_total_marks:string;
    level_3_obtained_marks:string;
    level_3_is_qualified:string;
    level_4_exam_date:string;
    level_4_total_marks:string;
    level_4_obtained_marks:string;
    level_4_is_qualified:string;
    level_5_exam_date:string;
    level_5_total_marks:string;
    level_5_obtained_marks:string;
    level_5_is_qualified:string;
    level_6_exam_date:string;
    level_6_total_marks:string;
    level_6_obtained_marks:string;
    level_6_is_qualified:string;
    level_7_exam_date:string;
    level_7_total_marks:string;
    level_7_obtained_marks:string;
    level_7_is_qualified:string;
    level_8_exam_date:string;
    level_8_total_marks:string;
    level_8_obtained_marks:string;
    level_8_is_qualified:string;
    level_9_exam_date:string;
    level_9_total_marks:string;
    level_9_obtained_marks:string;
    level_9_is_qualified:string;
  };

  export default devoteeNextLeveType;